[project]
name = "mcp-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.55.0",
    "pip>=25.1.1",
    "rich>=14.0.0",
]
